
name: algolia

on:
    push:
    workflow_dispatch:

jobs:

    upload_algolia_index:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: rxrw/algolia-index-uploader@v1
              with:
                algolia_index_id: ${{secrets.ALGOLIA_APP_ID}}
                algolia_index_admin_key: ${{secrets.ALGOLIA_ADMIN_KEY}}
                algolia_index_name: ${{secrets.ALGOLIA_INDEX_NAME}}
                index_path: ${{secrets.ALGOLIA_INDEX_FILE}}
