
name: algolia

on:
    push:
    workflow_dispatch:

jobs:

    upload_algolia_index:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
              env:
                APPLICATION_ID: ${{secrets.ALGOLIA_APP_ID}}
                ADMIN_API_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
                INDEX_NAME: ${{secrets.ALGOLIA_INDEX_NAME}}
                FILE_PATH: ${{secrets.ALGOLIA_INDEX_FILE}}
